### PR TITLE
The github integration is too buggy and too hard to work with

### PR DESCRIPTION
**Pull request by xavi-**
So I'm turning it off.

### CODE REVIEW

**Comment by nathanleiby** [comment]
nit: if you're leaving commented code, maybe link a JIRA ticket in the code like

```// TODO: Fix INFRA-123```

and then have a few things in that ticket for how to followup

**Comment by nathanleiby** [comment]
lgtm

**Comment by xavi-** [comment]
Added ticket number in comment.

**Comment by nathanleiby** [comment]
Thanks!

**Pull request merged**
