### PR TITLE
Upgraded gearcmd to v0.4.2

### PR DESCRIPTION
**Pull request by xavi-**

### CODE REVIEW

**Comment by burnsed** [comment]
LGTM

**Comment by natebrennand** [comment]
Don't we need to update the env vars to discovery format for this?

**Comment by xavi-** [comment]
@natebrennand Yep.  This past October we added discovery-compatible env-vars to all the then-existing pillars: https://github.com/Clever/salt/commit/d495917fc0327264677b5869515031245df9a20b

We did this to ease the adoption of discovery-go/node.

**Comment by natebrennand** [comment]
@xavi-: we should still update the launch file to reflect this

**Comment by xavi-** [comment]
@natebrennand Ahh, good catch.  I committed the change to the launch.yml directly to master.  Also made a PR to remove the old env-vars from salt: https://github.com/Clever/salt/pull/1399

**Pull request merged**
